"""
exporters/pdf_default.py
========================
Default PDF exporter using ReportLab.

This is the original PDF export format extracted from app.py.
To create your own PDF style, copy this file, rename the class,
change `name` and `label`, and rewrite `export()` to your liking.

Install dependency (already in requirements.txt):
    pip install reportlab
"""

import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
)

from exporters.base import BaseExporter


class DefaultPDFExporter(BaseExporter):
    name      = "pdf"
    label     = "PDF Document"
    mime_type = "application/pdf"
    extension = ".pdf"

    # ── Colours (override these in a subclass for a different theme) ──────
    PRIMARY_COLOUR  = "#2563eb"   # header / title blue
    HEADER_TEXT     = "#ffffff"   # column-table header text
    ROW_ALT         = "#f1f5f9"   # alternating row tint
    GRID_COLOUR     = "#d1d5db"   # table grid lines

    def export(self, data: dict, user, export_type: str, resources: list) -> bytes:
        buffer  = io.BytesIO()
        doc     = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            rightMargin=0.75 * inch,
        )

        elements = []
        styles   = getSampleStyleSheet()

        # ── Custom paragraph styles ────────────────────────────────────────
        title_style = ParagraphStyle(
            "DictTitle",
            parent=styles["Heading1"],
            fontSize=24,
            textColor=colors.HexColor(self.PRIMARY_COLOUR),
            spaceAfter=20,
            alignment=1,       # centre
        )
        schema_style = ParagraphStyle(
            "SchemaHeading",
            parent=styles["Heading2"],
            fontSize=14,
            textColor=colors.HexColor(self.PRIMARY_COLOUR),
            spaceBefore=18,
            spaceAfter=6,
        )
        table_style = ParagraphStyle(
            "TableHeading",
            parent=styles["Heading3"],
            fontSize=11,
            spaceBefore=10,
            spaceAfter=4,
        )
        desc_style = ParagraphStyle(
            "TableDesc",
            parent=styles["Normal"],
            fontSize=9,
            textColor=colors.grey,
            spaceAfter=6,
            leftIndent=6,
        )

        # ── Title ──────────────────────────────────────────────────────────
        elements.append(Paragraph("Data Dictionary", title_style))
        elements.append(Spacer(1, 0.15 * inch))

        # ── Metadata table ─────────────────────────────────────────────────
        meta = data.get("meta", {})
        meta_rows = [
            ["Generated by:",  meta.get("generated_by", "—")],
            ["Generated at:",  meta.get("generated_at", "—")],
            ["Export type:",   meta.get("export_type", export_type).capitalize()],
        ]
        meta_tbl = Table(meta_rows, colWidths=[1.8 * inch, 4.5 * inch])
        meta_tbl.setStyle(TableStyle([
            ("FONTNAME",  (0, 0), (-1, -1), "Helvetica"),
            ("FONTSIZE",  (0, 0), (-1, -1), 9),
            ("TEXTCOLOR", (0, 0), (0, -1),  colors.grey),
            ("ALIGN",     (0, 0), (-1, -1), "LEFT"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]))
        elements.append(meta_tbl)
        elements.append(Spacer(1, 0.3 * inch))

        # ── Schemas → Tables → Columns ────────────────────────────────────
        primary = colors.HexColor(self.PRIMARY_COLOUR)
        header_text = colors.HexColor(self.HEADER_TEXT)
        row_alt = colors.HexColor(self.ROW_ALT)
        grid = colors.HexColor(self.GRID_COLOUR)

        for schema in data.get("schemas", []):
            elements.append(Paragraph(f"Schema: {schema['name']}", schema_style))

            for tbl in schema.get("tables", []):
                elements.append(Paragraph(f"Table: {tbl['name']}", table_style))

                desc = tbl.get("description") or "No description"
                elements.append(Paragraph(desc, desc_style))

                columns = tbl.get("columns", [])
                if columns:
                    # Header row + data rows
                    col_data = [["Column", "Type", "Description"]]
                    for col in columns:
                        raw_desc = col.get("description", "")
                        col_data.append([
                            col.get("name", ""),
                            col.get("data_type", ""),
                            (raw_desc[:80] + "…") if len(raw_desc) > 80 else raw_desc,
                        ])

                    col_tbl = Table(
                        col_data,
                        colWidths=[1.5 * inch, 1.4 * inch, 3.85 * inch],
                        repeatRows=1,
                    )

                    # Alternating row colours
                    row_styles = [
                        # Header
                        ("BACKGROUND",    (0, 0),  (-1, 0),  primary),
                        ("TEXTCOLOR",     (0, 0),  (-1, 0),  header_text),
                        ("FONTNAME",      (0, 0),  (-1, 0),  "Helvetica-Bold"),
                        ("FONTSIZE",      (0, 0),  (-1, 0),  9),
                        ("BOTTOMPADDING", (0, 0),  (-1, 0),  8),
                        # Body
                        ("FONTNAME",      (0, 1),  (-1, -1), "Helvetica"),
                        ("FONTSIZE",      (0, 1),  (-1, -1), 8),
                        ("ALIGN",         (0, 0),  (-1, -1), "LEFT"),
                        ("VALIGN",        (0, 0),  (-1, -1), "TOP"),
                        ("GRID",          (0, 0),  (-1, -1), 0.4, grid),
                        ("TOPPADDING",    (0, 1),  (-1, -1), 4),
                        ("BOTTOMPADDING", (0, 1),  (-1, -1), 4),
                    ]
                    # Tint even rows
                    for i in range(2, len(col_data), 2):
                        row_styles.append(("BACKGROUND", (0, i), (-1, i), row_alt))

                    col_tbl.setStyle(TableStyle(row_styles))
                    elements.append(col_tbl)

                elements.append(Spacer(1, 0.25 * inch))

            elements.append(PageBreak())

        doc.build(elements)
        buffer.seek(0)
        return buffer.getvalue()
